# Generated by Django 3.1.3 on 2021-01-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_gamerevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametype',
            old_name='type',
            new_name='label',
        ),
    ]
